### PR TITLE
apiserver: fix file descriptor leak in exec

### LINKED ISSUE #572: apiclient does not close opened file descriptors
version=1.32

**Package I'm using:**
apiclient

**What I expected to happen:**
open fd should not increase once the command is completed.

**What actually happened:**

open fd count keeps increasing as I run more and more commands and eventually hits limit of 1024 and becomes unusable.

**How to reproduce the problem:**

pid
```
[root@admin]# ps aux | grep 1359
root        1359  0.0  0.0 754420  9004 ?        Ssl  05:28   0:02 /usr/bin/apiserver --datastore-path /var/lib/bottlerocket/
```

initial count
```
[root@admin]# for pid in /proc/[0-9]*; do echo "$(ls -l $pid/fd 2>/dev/null | wc -l) $pid"; done | sort -nr | head -n 10
398 /proc/1359
54 /proc/1
45 /proc/1912
35 /proc/378
31 /proc/1913
24 /proc/2153
23 /proc/1631
19 /proc/1302
18 /proc/3365
18 /proc/1306
```

run command one or more times.

```
[root@admin]# apiclient exec admin  echo hello && echo world
hello
world
[root@admin]# for pid in /proc/[0-9]*; do echo "$(ls -l $pid/fd 2>/dev/null | wc -l) $pid"; done | sort -nr | head -n 10
399 /proc/1359
54 /proc/1
45 /proc/1912
35 /proc/378
31 /proc/1913
24 /proc/2153
23 /proc/1631
19 /proc/1302
18 /proc/3365
18 /proc/1306
[root@admin]# apiclient exec admin  echo hello && echo world
hello
world
[root@admin]# for pid in /proc/[0-9]*; do echo "$(ls -l $pid/fd 2>/dev/null | wc -l) $pid"; done | sort -nr | head -n 10
400 /proc/1359
54 /proc/1
50 /proc/1912
35 /proc/378
31 /proc/1913
24 /proc/2153
23 /proc/1631
19 /proc/1302
18 /proc/3365
18 /proc/1306
```

checked after few mins

```
[root@admin]# for pid in /proc/[0-9]*; do echo "$(ls -l $pid/fd 2>/dev/null | wc -l) $pid"; done | sort -nr | head -n 10
400 /proc/1359
54 /proc/1
40 /proc/1912
35 /proc/378
31 /proc/1913
24 /proc/2153
23 /proc/1631
19 /proc/1302
18 /proc/3365
18 /proc/1306
```

### PR DESCRIPTION
**Pull request by KCSesh**
**Issue number:**

Closes #572

**Description of changes:**
The [ChildHandles](https://github.com/bottlerocket-os/bottlerocket-core-kit/blob/0551078bb322ab7d30c5cf2c707a0b87452a3eae/sources/api/apiserver/src/server/exec/child.rs#L53C19-L53C31) struct was not implementing the Drop trait to properly close the
raw file descriptor (pty_fd) when the struct was dropped. 

Unlike `write_fd` which is wrapped in a File object with automatic cleanup, this raw `pty_fd` requires explicit closure to
prevent leaks. 

**Testing done:**
* Enabled debug logs on api server and performed several  apiclient exec commands
* Confirmed this happens with and without TTY

Reaches Max Limit of fds before change / works after
```
for i in {1..1500}; do
  echo "Iteration $i"
  apiclient exec admin ls -la > /dev/null &
  echo "FD count: $(ls -l /proc/$(pgrep apiserver)/fd | wc -l)"
done
```

Before the change:

```
bash-4.2#  ls -la /proc/1535/fd | wc -l
25
bash-4.2# apiclient exec admin echo hello
hello
bash-4.2# ls -la /proc/1535/fd | wc -l
26
```

After the change:
```
bash-5.1# ls -la /proc/$(pgrep apiserver)/fd/ | wc -l
22
bash-5.1# apiclient exec -T control echo test
test
bash-5.1# ls -la /proc/$(pgrep apiserver)/fd/ | wc -l
22
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: sources/api/apiserver/src/server/exec/child.rs [hunk 1]
```diff
@@ -241,6 +241,16 @@ impl ChildHandles {
...
 }
 
+impl Drop for ChildHandles {
+    /// Ensures the RawFd is properly closed when ChildHandles is dropped.
+    fn drop(&mut self) {
+        match close(self.pty_fd) {
+            Ok(_) => debug!("Closed file descriptor: {}", self.pty_fd),
+            Err(e) => warn!("Failed to close file descriptor {}: {}", self.pty_fd, e),
+        }
+    }
```
Comment (bcressey) [inline sources/api/apiserver/src/server/exec/child.rs]: Not sure we want to do much or any logging in a `Drop` impl:

```suggestion
    fn drop(&mut self) {
        let _ = close(self.pty_fd);
    }
```

Comment (KCSesh) [reply sources/api/apiserver/src/server/exec/child.rs]: Fair 👍 I saw we did a warning in [Termina's Drop](https://github.com/bottlerocket-os/bottlerocket-core-kit/blob/develop/sources/api/apiclient/src/exec/terminal.rs#L93) but I agree it doesn't add much value.

File: sources/api/apiserver/src/server/exec/child.rs [hunk 2]
```diff
@@ -241,6 +241,13 @@ impl ChildHandles {
     }
 }
 
+impl Drop for ChildHandles {
```
Comment (arnaldo2792) [inline sources/api/apiserver/src/server/exec/child.rs:244]: Just to confirm, you still get the "ERROR" after the `apiclient exec` command completes, right?

**Review by bcressey — APPROVED** [review]

**Review by arnaldo2792 — APPROVED** [review]

File: sources/api/apiserver/src/server/exec/child.rs [hunk 3]
```diff
@@ -241,6 +241,13 @@ impl ChildHandles {
...
+    /// Ensures the RawFd is properly closed when ChildHandles is dropped.
+    fn drop(&mut self) {
+        let _ = close(self.pty_fd);
```
Comment (ytsssun) [inline sources/api/apiserver/src/server/exec/child.rs:247]: nit: drop the `let` statement given that the output of close() is not really used?

**Review by ytsssun — APPROVED** [review]
